# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-23 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20171023_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cell_phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='zipcode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cell_phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='zipcode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='qty_on_hand',
            field=models.IntegerField(),
        ),
    ]