# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-11 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='id',
        ),
        migrations.AddField(
            model_name='visit',
            name='client_number',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Client', to='portfolio.Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='emp_number',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Employee', to='portfolio.Employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='status',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='client_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
