# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-12 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20171111_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_number',
            field=models.IntegerField(default='', primary_key=True, serialize=False),
        ),
    ]
