# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-11 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20171111_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='client_number',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='emp_number',
        ),
        migrations.AddField(
            model_name='visit',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='portfolio.Client'),
        ),
        migrations.AddField(
            model_name='visit',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='visit',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='portfolio.Employee'),
        ),
    ]
