# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-12 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20171111_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(default='status', max_length=50),
        ),
    ]
