# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-13 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20171111_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
