# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-12 00:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20171110_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
