# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-13 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20171113_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='visit',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='portfolio.Visit'),
        ),
    ]
